wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.1
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.3
    start_time: 1646661112
    t:
      1:
      - 2
      - 3
      - 5
      2:
      - 2
      - 3
      - 5
      3:
      - 2
      4: 3.7.3
      5: 0.12.1
      8:
      - 5
